services:
  ollama:
    image: ollama/ollama
    container_name: clinicops-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  pg-client:
    image: postgres:16-alpine
    container_name: clinicops-pg-client
    working_dir: /workspace/backend
    command: ["sh", "-c", "sleep infinity"]
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ./:/workspace

volumes:
  ollama:
